---
title: "EAA Interactive Presentation"
format: revealjs
editor: visual
---

```{r}

#| echo: false
#| message: false

library(tidyverse)
library(patchwork)
library(lubridate)
library(showtext)
library(sysfonts)


source("function_ribbon.R")
source("function_bin_map_interactive.R")
source("branded_style.R")

#presets
sysfonts::font_add_google("Open Sans", family = "Open Sans")
showtext::showtext_auto()


cumulative_subbasin<-read.csv("../data/processed/cumulative_subbasin.csv")|>
    mutate(date = as.Date(date))

basins<-cumulative_subbasin|>filter(basin!='usgs_dissolved')|>distinct(basin)|>pull()

map <- sf::read_sf("../data/gis/clipped_hrap/usgs_recharge_basins/usgs_dissolved.shp")
streams <- read_sf("../data/gis/boundaries_features/streams_recharge.shp")
lakes <- read_sf("../data/gis/boundaries_features/reservoirs.shp")
tx_rain <- arrow::open_dataset("../data/parquet/parquet_files")

sum_rain_query <- tx_rain %>%
  filter(year==2015) %>%
  group_by (grib_id) %>%
  summarize(
    sum_rain = sum(rain_mm, na.rm=TRUE)) %>%
  arrange(desc(sum_rain))

tic()
sum_rain_collect <- collect(sum_rain_query)
toc(quiet = TRUE)  

map_rain <- map|>
  left_join(sum_rain_collect, by = "grib_id")|>
  mutate(cubic_m_precip = bin_area * sum_rain * 0.001)

```


## Recharge Zone Map - Light Mode

```{r}
#| fig-width: 12
#| fig-height: 6
girafe(ggobj = plot_bin_map_interactive(subtitle= "September 2015 Precipitation. STG4 QPE BIN 4km.",
              map_rain = map_rain,
              map_streams = streams,
              map_lakes = lakes,
             # pal_water='#657275',
              pal_water = '#2C6690',
              pal_title='black',
              pal_legend = 'YlGnBu',
              bin_alpha = 0.9,
              pal_subtitle='black',
              pal_outline="white",
              pal_bin_outline='white',
              pal_legend_text='black',
              map_type='cartolight'),
       width_svg = 12,
       height_svg = 6.5,
       options = list(
         opts_tooltip(css="font-family:Open Sans;background:black;color:white;padding:3px 6px;border-radius:2px"),
         opts_toolbar(saveaspng = F)
         )
       )

```


## Combo Plot

```{r}
#| fig-width: 11.5
#| fig-height: 5.3

precip_facet<-plot_ribbon_facet(
  data = cumulative_subbasin, 
  basins = basins, 
  pal_avg = style$pal$orange,
  pal_title = "black",
  title = NA,
  subtitle = "Subbasin Level",
  caption = NA,
  legend = T
  )


precip_total<-plot_ribbon(
  data = cumulative_subbasin, 
  select_basin = "usgs_dissolved", 
  pal_avg = style$pal$orange,
  pal_title = "black",
  title = NA,
  subtitle = "Basin Level",
  caption = NA)



(guide_area() + 
    (
      precip_total + 
      (precip_facet & theme(axis.text = element_text(size=7), strip.text = element_text(size=7))) +
      plot_layout(widths=c(1.25,1.5)))
      ) +
  plot_layout(
    guides = "collect", 
    heights = unit(c(0.1, 0.1), c("cm", "null")),
  ) + 
  plot_annotation(
    title = "Cumulative Precipitation Year-to-Date",
    subtitle = "Comparison of average and median rainfall (mm) year to date for basins and subbasins.",
  #  caption = "Source: Edwards Aquifer Authority"
  ) & 
  theme(
    text = element_text(family = style$font, size = 12),
    plot.title = element_text(face = 'bold'),
  #  plot.caption = element_text(hjust = 0, color="grey60"),
    legend.justification = c(-0.04, 0),
    legend.title = element_blank(),
    legend.margin = margin(0, 0, 0, 0),
    plot.margin = margin(rep(10,4)) 
  )

```
